# Generated by Django 4.2.1 on 2023-05-17 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
