# Generated by Django 4.2.1 on 2023-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0002_alter_activesession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesession',
            name='user_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
