# Generated by Django 4.2.1 on 2023-05-16 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_password', models.CharField(max_length=32)),
                ('e_gender', models.CharField(max_length=25)),
                ('e_contact', models.CharField(max_length=100)),
                ('e_address', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('organisation_contact', models.CharField(max_length=100)),
                ('orgaisation_website', models.CharField(max_length=100)),
                ('organisation_address', models.CharField(max_length=150)),
                ('orgnisation_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('peoject_description', models.CharField(max_length=200)),
                ('Organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='WorkProductivityDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_pds', models.CharField(max_length=255)),
                ('w_type', models.CharField(max_length=255)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
            ],
            options={
                'db_table': 'WorkProductivityDataset',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=55)),
                ('task_desc', models.CharField(max_length=200)),
                ('task_status', models.CharField(max_length=55)),
                ('task_priority', models.CharField(max_length=30)),
                ('task_assign_date', models.CharField(max_length=55)),
                ('task_deadline_date', models.CharField(max_length=55)),
                ('task_update_date', models.CharField(max_length=55, null=True)),
                ('Employe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeids', to='dashboard.employe')),
                ('Project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectids', to='dashboard.project')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardids', to='dashboard.board')),
                ('orgnisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='MonitoringDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_title', models.CharField(max_length=200)),
                ('md_total_time_seconds', models.CharField(max_length=200)),
                ('md_date', models.CharField(max_length=200)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employe')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
            ],
            options={
                'db_table': 'MonitoringDetails',
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_title', models.CharField(max_length=200, null=True)),
                ('monitaring_log_ts', models.CharField(max_length=200)),
                ('Employe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employe')),
                ('orgnisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
            ],
            options={
                'db_table': 'monitoring',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=55)),
                ('m_desc', models.CharField(max_length=200)),
                ('m_uuid', models.CharField(max_length=200)),
                ('m_start_date', models.CharField(max_length=55)),
                ('m_stop_date', models.CharField(max_length=55)),
                ('m_start_time', models.CharField(max_length=55)),
                ('m_stop_time', models.CharField(max_length=55)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='Organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization'),
        ),
        migrations.AddField(
            model_name='board',
            name='orgnisation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization'),
        ),
        migrations.CreateModel(
            name='AttendanceLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendance_date', models.CharField(max_length=55)),
                ('attendance_time', models.CharField(max_length=55)),
                ('attendance_status', models.CharField(max_length=55)),
                ('attendance_ip_address', models.CharField(max_length=55)),
                ('attendance_time_zone', models.CharField(max_length=55)),
                ('attendance_lat', models.CharField(max_length=55)),
                ('attendance_long', models.CharField(max_length=55)),
                ('employe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employe')),
                ('orgnisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
            ],
            options={
                'db_table': 'AttendanceLogs',
            },
        ),
        migrations.CreateModel(
            name='Project_Employee_Linker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employe')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
            ],
            options={
                'db_table': 'project_emp_assign',
                'unique_together': {('p_id', 'e_id', 'o_id')},
            },
        ),
    ]
