# Generated by Django 3.2.19 on 2023-06-24 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=100)),
                ('orgnisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('e_gender', models.CharField(max_length=25)),
                ('e_contact', models.CharField(max_length=100)),
                ('e_address', models.CharField(max_length=150)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgid', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employe',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('peoject_description', models.CharField(max_length=200)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='WorkProductivityDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_pds', models.CharField(max_length=255)),
                ('w_type', models.CharField(max_length=255)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WorkProductivityDataset',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=55)),
                ('team_desc', models.CharField(max_length=300)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='dashboard.board')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=55)),
                ('task_desc', models.CharField(max_length=200)),
                ('task_status', models.CharField(max_length=55)),
                ('task_priority', models.CharField(max_length=30)),
                ('task_assign_date', models.CharField(max_length=55)),
                ('task_deadline_date', models.CharField(max_length=55)),
                ('task_update_date', models.CharField(max_length=55, null=True)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardids', to='dashboard.board')),
                ('employe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeids', to='dashboard.employe')),
                ('orgnisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectids', to='dashboard.project')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(default=None, max_length=100, null=True)),
                ('website', models.CharField(default=None, max_length=100, null=True)),
                ('address', models.CharField(default=None, max_length=150, null=True)),
                ('location', models.CharField(default=None, max_length=150, null=True)),
                ('Gender', models.CharField(default=None, max_length=160, null=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_title', models.CharField(max_length=200)),
                ('md_total_time_seconds', models.CharField(max_length=200)),
                ('md_date', models.CharField(max_length=200)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employe')),
                ('orgnisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MonitoringDetails',
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_title', models.CharField(max_length=200, null=True)),
                ('monitaring_log_ts', models.CharField(max_length=200)),
                ('Employe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employe')),
                ('orgnisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=55)),
                ('m_desc', models.CharField(max_length=200)),
                ('m_uuid', models.CharField(max_length=200)),
                ('m_start_date', models.CharField(max_length=55)),
                ('m_stop_date', models.CharField(max_length=55)),
                ('m_start_time', models.CharField(max_length=55)),
                ('m_stop_time', models.CharField(max_length=55)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendance_date', models.CharField(max_length=55)),
                ('attendance_time', models.CharField(max_length=55)),
                ('attendance_status', models.CharField(max_length=55)),
                ('attendance_ip_address', models.CharField(max_length=55)),
                ('attendance_time_zone', models.CharField(max_length=55)),
                ('attendance_lat', models.CharField(max_length=55)),
                ('attendance_long', models.CharField(max_length=55)),
                ('employe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employe')),
                ('orgnisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AttendanceLogs',
            },
        ),
        migrations.CreateModel(
            name='Project_Employee_Linker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employe')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
            ],
            options={
                'db_table': 'project_emp_assign',
                'unique_together': {('p_id', 'e_id', 'o_id')},
            },
        ),
    ]
