# Generated by Django 3.2.19 on 2023-06-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='user',
        ),
    ]
