# Generated by Django 4.2.1 on 2023-08-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_attendancelogs_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelogs',
            name='login_time',
            field=models.CharField(max_length=130),
        ),
    ]
