# Generated by Django 3.2.19 on 2023-06-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_employe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='user',
        ),
    ]
