# Generated by Django 4.2.1 on 2023-05-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_attendancelogs_orgnisation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='Organization_id',
            new_name='organization_id',
        ),
    ]
