# Generated by Django 4.2.1 on 2023-05-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_organization_id_employe_organization_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoringdetails',
            old_name='o_id',
            new_name='orgnisation_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Organization_id',
            new_name='organization_id',
        ),
    ]
