# Generated by Django 4.2.1 on 2023-08-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_logginout_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logginout',
            name='total_time',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
    ]
