# Generated by Django 3.2.19 on 2023-06-26 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_alter_employe_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='users',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='api_user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgid', to=settings.AUTH_USER_MODEL),
        ),
    ]
