# Generated by Django 4.2.1 on 2023-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_screenshotsmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideltime',
            name='localtime',
            field=models.CharField(default=False, max_length=140),
        ),
        migrations.AlterField(
            model_name='ideltime',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ideltime',
            name='idealtime',
            field=models.CharField(max_length=140),
        ),
    ]
