# Generated by Django 4.2.1 on 2023-05-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Employe_id',
            new_name='employe_id',
        ),
    ]
