# Generated by Django 4.2.1 on 2023-08-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_ideltime_localtime_alter_ideltime_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktopfile',
            old_name='name',
            new_name='desktopfile_name',
        ),
    ]
