# Generated by Django 4.2.1 on 2023-05-31 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_employe_id_task_employe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Project_id',
            new_name='project_id',
        ),
    ]
