# Generated by Django 3.2.19 on 2023-06-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_project_id_task_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=55)),
                ('team_desc', models.CharField(max_length=300)),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.board')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
