# Generated by Django 3.2.19 on 2023-06-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20230623_2111'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
    ]
