# Generated by Django 3.2.19 on 2023-06-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_team_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='boardid',
        ),
        migrations.AddField(
            model_name='team',
            name='board_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='dashboard.board'),
            preserve_default=False,
        ),
    ]
