# Generated by Django 3.2.19 on 2023-07-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_screenshotsmodel_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshotsmodel',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employe'),
        ),
    ]
