# Generated by Django 3.2.19 on 2023-06-23 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_auto_20230623_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='organization_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_user.user'),
            preserve_default=False,
        ),
    ]
