# Generated by Django 3.2.19 on 2023-07-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_screenshotsmodel_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshotsmodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
