# Generated by Django 3.2.19 on 2023-07-08 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_screenshotsmodel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelogs',
            old_name='orgnisation_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='attendancelogs',
            name='atendance_date',
        ),
        migrations.RemoveField(
            model_name='attendancelogs',
            name='attendance_ip_address',
        ),
        migrations.RemoveField(
            model_name='attendancelogs',
            name='attendance_lat',
        ),
        migrations.RemoveField(
            model_name='attendancelogs',
            name='attendance_long',
        ),
        migrations.RemoveField(
            model_name='attendancelogs',
            name='attendance_status',
        ),
        migrations.RemoveField(
            model_name='attendancelogs',
            name='attendance_time',
        ),
        migrations.RemoveField(
            model_name='attendancelogs',
            name='attendance_time_zone',
        ),
        migrations.RemoveField(
            model_name='attendancelogs',
            name='employe_id',
        ),
        migrations.AddField(
            model_name='attendancelogs',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendancelogs',
            name='login_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='attendancelogs',
            name='logout_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='attendancelogs',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
        ),
    ]
