# Generated by Django 3.2.19 on 2023-07-08 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20230708_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelogs',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendancelogs',
            name='logout_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
