# Generated by Django 3.2.19 on 2023-07-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20230708_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelogs',
            old_name='status',
            new_name='work_status',
        ),
    ]
