# Generated by Django 4.2.1 on 2023-07-11 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_status_attendancelogs_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelogs',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancelogs',
            name='login_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancelogs',
            name='logout_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
