# Generated by Django 3.2.19 on 2023-07-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_attendancelogs_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelogs',
            name='date',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='attendancelogs',
            name='login_time',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='attendancelogs',
            name='logout_time',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='attendancelogs',
            name='work_status',
            field=models.CharField(max_length=120),
        ),
    ]
