# Generated by Django 3.2.19 on 2023-07-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20230712_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelogs',
            name='date',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancelogs',
            name='login_time',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancelogs',
            name='logout_time',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancelogs',
            name='work_status',
            field=models.DateTimeField(default=True),
        ),
    ]
