# Generated by Django 3.2.19 on 2023-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20230712_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelogs',
            name='work_status',
            field=models.CharField(max_length=120),
        ),
    ]
