# Generated by Django 4.2.1 on 2023-07-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_attendancelogs_work_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoring',
            old_name='monitaring_log_ts',
            new_name='screen_name',
        ),
        migrations.RenameField(
            model_name='monitoring',
            old_name='monitoring_title',
            new_name='screen_title',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='Employe_id',
        ),
        migrations.RemoveField(
            model_name='monitoringdetails',
            name='e_id',
        ),
    ]
