# Generated by Django 4.2.1 on 2023-07-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_monitaring_log_ts_monitoring_screen_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoring',
            old_name='screen_title',
            new_name='screen_count',
        ),
    ]
