# Generated by Django 4.2.1 on 2023-07-19 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0027_rename_screen_title_monitoring_screen_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelogs',
            name='logout_time',
        ),
        migrations.CreateModel(
            name='logginout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(auto_now_add=True)),
                ('endreport', models.CharField(default=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loggingout',
            },
        ),
    ]
