# Generated by Django 4.2.1 on 2023-08-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='m_desc',
            new_name='meating_description',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='m_name',
            new_name='meating_name',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='m_start_date',
            new_name='meating_start_time',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='m_uuid',
            new_name='meating_url',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='o_id',
            new_name='organisation_id',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='p_id',
            new_name='project_id',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='m_start_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='m_stop_date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='m_stop_time',
        ),
    ]
