# Generated by Django 4.2.1 on 2023-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_rename_m_desc_meeting_meating_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='project_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
