# Generated by Django 4.2.1 on 2023-05-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_user_orgaisation_website_user_organisation_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='orgaisation_website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization_name',
        ),
    ]
